#define __NR_NtAcceptConnectPort 0
#define __NR_NtAccessCheck 1
#define __NR_NtAccessCheckAndAuditAlarm 2
#define __NR_NtAccessCheckByType 3
#define __NR_NtAccessCheckByTypeAndAuditAlarm 4
#define __NR_NtAccessCheckByTypeResultList 5
#define __NR_NtAccessCheckByTypeResultListAndAuditAlarm 6
#define __NR_NtAccessCheckByTypeResultListAndAuditAlarmByHandle 7
#define __NR_NtAddAtom 8
#define __NR_NtAddBootEntry 9
#define __NR_NtAddDriverEntry 10
#define __NR_NtAdjustGroupsToken 11
#define __NR_NtAdjustPrivilegesToken 12
#define __NR_NtAlertResumeThread 13
#define __NR_NtAlertThread 14
#define __NR_NtAllocateLocallyUniqueId 15
#define __NR_NtAllocateReserveObject 16
#define __NR_NtAllocateUserPhysicalPages 17
#define __NR_NtAllocateUuids 18
#define __NR_NtAllocateVirtualMemory 19
#define __NR_NtAlpcAcceptConnectPort 20
#define __NR_NtAlpcCancelMessage 21
#define __NR_NtAlpcConnectPort 22
#define __NR_NtAlpcCreatePort 23
#define __NR_NtAlpcCreatePortSection 24
#define __NR_NtAlpcCreateResourceReserve 25
#define __NR_NtAlpcCreateSectionView 26
#define __NR_NtAlpcCreateSecurityContext 27
#define __NR_NtAlpcDeletePortSection 28
#define __NR_NtAlpcDeleteResourceReserve 29
#define __NR_NtAlpcDeleteSectionView 30
#define __NR_NtAlpcDeleteSecurityContext 31
#define __NR_NtAlpcDisconnectPort 32
#define __NR_NtAlpcImpersonateClientOfPort 33
#define __NR_NtAlpcOpenSenderProcess 34
#define __NR_NtAlpcOpenSenderThread 35
#define __NR_NtAlpcQueryInformation 36
#define __NR_NtAlpcQueryInformationMessage 37
#define __NR_NtAlpcRevokeSecurityContext 38
#define __NR_NtAlpcSendWaitReceivePort 39
#define __NR_NtAlpcSetInformation 40
#define __NR_NtApphelpCacheControl 41
#define __NR_NtAreMappedFilesTheSame 42
#define __NR_NtAssignProcessToJobObject 43
#define __NR_NtCallbackReturn 44
#define __NR_NtCancelIoFile 45
#define __NR_NtCancelIoFileEx 46
#define __NR_NtCancelSynchronousIoFile 47
#define __NR_NtCancelTimer 48
#define __NR_NtClearEvent 49
#define __NR_NtClose 50
#define __NR_NtCloseObjectAuditAlarm 51
#define __NR_NtCommitComplete 52
#define __NR_NtCommitEnlistment 53
#define __NR_NtCommitTransaction 54
#define __NR_NtCompactKeys 55
#define __NR_NtCompareTokens 56
#define __NR_NtCompleteConnectPort 57
#define __NR_NtCompressKey 58
#define __NR_NtConnectPort 59
#define __NR_NtContinue 60
#define __NR_NtCreateDebugObject 61
#define __NR_NtCreateDirectoryObject 62
#define __NR_NtCreateEnlistment 63
#define __NR_NtCreateEvent 64
#define __NR_NtCreateEventPair 65
#define __NR_NtCreateFile 66
#define __NR_NtCreateIoCompletion 67
#define __NR_NtCreateJobObject 68
#define __NR_NtCreateJobSet 69
#define __NR_NtCreateKey 70
#define __NR_NtCreateKeyTransacted 72
#define __NR_NtCreateKeyedEvent 71
#define __NR_NtCreateMailslotFile 73
#define __NR_NtCreateMutant 74
#define __NR_NtCreateNamedPipeFile 75
#define __NR_NtCreatePagingFile 76
#define __NR_NtCreatePort 77
#define __NR_NtCreatePrivateNamespace 78
#define __NR_NtCreateProcess 79
#define __NR_NtCreateProcessEx 80
#define __NR_NtCreateProfile 81
#define __NR_NtCreateProfileEx 82
#define __NR_NtCreateResourceManager 83
#define __NR_NtCreateSection 84
#define __NR_NtCreateSemaphore 85
#define __NR_NtCreateSymbolicLinkObject 86
#define __NR_NtCreateThread 87
#define __NR_NtCreateThreadEx 88
#define __NR_NtCreateTimer 89
#define __NR_NtCreateToken 90
#define __NR_NtCreateTransaction 91
#define __NR_NtCreateTransactionManager 92
#define __NR_NtCreateUserProcess 93
#define __NR_NtCreateWaitablePort 94
#define __NR_NtCreateWorkerFactory 95
#define __NR_NtDebugActiveProcess 96
#define __NR_NtDebugContinue 97
#define __NR_NtDelayExecution 98
#define __NR_NtDeleteAtom 99
#define __NR_NtDeleteBootEntry 100
#define __NR_NtDeleteDriverEntry 101
#define __NR_NtDeleteFile 102
#define __NR_NtDeleteKey 103
#define __NR_NtDeleteObjectAuditAlarm 104
#define __NR_NtDeletePrivateNamespace 105
#define __NR_NtDeleteValueKey 106
#define __NR_NtDeviceIoControlFile 107
#define __NR_NtDisableLastKnownGood 108
#define __NR_NtDisplayString 109
#define __NR_NtDrawText 110
#define __NR_NtDuplicateObject 111
#define __NR_NtDuplicateToken 112
#define __NR_NtEnableLastKnownGood 113
#define __NR_NtEnumerateBootEntries 114
#define __NR_NtEnumerateDriverEntries 115
#define __NR_NtEnumerateKey 116
#define __NR_NtEnumerateSystemEnvironmentValuesEx 117
#define __NR_NtEnumerateTransactionObject 118
#define __NR_NtEnumerateValueKey 119
#define __NR_NtExtendSection 120
#define __NR_NtFilterToken 121
#define __NR_NtFindAtom 122
#define __NR_NtFlushBuffersFile 123
#define __NR_NtFlushInstallUILanguage 124
#define __NR_NtFlushInstructionCache 125
#define __NR_NtFlushKey 126
#define __NR_NtFlushProcessWriteBuffers 127
#define __NR_NtFlushVirtualMemory 128
#define __NR_NtFlushWriteBuffer 129
#define __NR_NtFreeUserPhysicalPages 130
#define __NR_NtFreeVirtualMemory 131
#define __NR_NtFreezeRegistry 132
#define __NR_NtFreezeTransactions 133
#define __NR_NtFsControlFile 134
#define __NR_NtGetContextThread 135
#define __NR_NtGetCurrentProcessorNumber 136
#define __NR_NtGetDevicePowerState 137
#define __NR_NtGetMUIRegistryInfo 138
#define __NR_NtGetNextProcess 139
#define __NR_NtGetNextThread 140
#define __NR_NtGetNlsSectionPtr 141
#define __NR_NtGetNotificationResourceManager 142
#define __NR_NtGetPlugPlayEvent 143
#define __NR_NtGetWriteWatch 144
#define __NR_NtImpersonateAnonymousToken 145
#define __NR_NtImpersonateClientOfPort 146
#define __NR_NtImpersonateThread 147
#define __NR_NtInitializeNlsFiles 148
#define __NR_NtInitializeRegistry 149
#define __NR_NtInitiatePowerAction 150
#define __NR_NtIsProcessInJob 151
#define __NR_NtIsSystemResumeAutomatic 152
#define __NR_NtIsUILanguageComitted 153
#define __NR_NtListenPort 154
#define __NR_NtLoadDriver 155
#define __NR_NtLoadKey 156
#define __NR_NtLoadKey2 157
#define __NR_NtLoadKeyEx 158
#define __NR_NtLockFile 159
#define __NR_NtLockProductActivationKeys 160
#define __NR_NtLockRegistryKey 161
#define __NR_NtLockVirtualMemory 162
#define __NR_NtMakePermanentObject 163
#define __NR_NtMakeTemporaryObject 164
#define __NR_NtMapCMFModule 165
#define __NR_NtMapUserPhysicalPages 166
#define __NR_NtMapUserPhysicalPagesScatter 167
#define __NR_NtMapViewOfSection 168
#define __NR_NtModifyBootEntry 169
#define __NR_NtModifyDriverEntry 170
#define __NR_NtNotifyChangeDirectoryFile 171
#define __NR_NtNotifyChangeKey 172
#define __NR_NtNotifyChangeMultipleKeys 173
#define __NR_NtNotifyChangeSession 174
#define __NR_NtOpenDirectoryObject 175
#define __NR_NtOpenEnlistment 176
#define __NR_NtOpenEvent 177
#define __NR_NtOpenEventPair 178
#define __NR_NtOpenFile 179
#define __NR_NtOpenIoCompletion 180
#define __NR_NtOpenJobObject 181
#define __NR_NtOpenKey 182
#define __NR_NtOpenKeyEx 183
#define __NR_NtOpenKeyTransacted 185
#define __NR_NtOpenKeyTransactedEx 186
#define __NR_NtOpenKeyedEvent 184
#define __NR_NtOpenMutant 187
#define __NR_NtOpenObjectAuditAlarm 188
#define __NR_NtOpenPrivateNamespace 189
#define __NR_NtOpenProcess 190
#define __NR_NtOpenProcessToken 191
#define __NR_NtOpenProcessTokenEx 192
#define __NR_NtOpenResourceManager 193
#define __NR_NtOpenSection 194
#define __NR_NtOpenSemaphore 195
#define __NR_NtOpenSession 196
#define __NR_NtOpenSymbolicLinkObject 197
#define __NR_NtOpenThread 198
#define __NR_NtOpenThreadToken 199
#define __NR_NtOpenThreadTokenEx 200
#define __NR_NtOpenTimer 201
#define __NR_NtOpenTransaction 202
#define __NR_NtOpenTransactionManager 203
#define __NR_NtPlugPlayControl 204
#define __NR_NtPowerInformation 205
#define __NR_NtPrePrepareComplete 208
#define __NR_NtPrePrepareEnlistment 209
#define __NR_NtPrepareComplete 206
#define __NR_NtPrepareEnlistment 207
#define __NR_NtPrivilegeCheck 210
#define __NR_NtPrivilegeObjectAuditAlarm 212
#define __NR_NtPrivilegedServiceAuditAlarm 211
#define __NR_NtPropagationComplete 213
#define __NR_NtPropagationFailed 214
#define __NR_NtProtectVirtualMemory 215
#define __NR_NtPulseEvent 216
#define __NR_NtQueryAttributesFile 217
#define __NR_NtQueryBootEntryOrder 218
#define __NR_NtQueryBootOptions 219
#define __NR_NtQueryDebugFilterState 220
#define __NR_NtQueryDefaultLocale 221
#define __NR_NtQueryDefaultUILanguage 222
#define __NR_NtQueryDirectoryFile 223
#define __NR_NtQueryDirectoryObject 224
#define __NR_NtQueryDriverEntryOrder 225
#define __NR_NtQueryEaFile 226
#define __NR_NtQueryEvent 227
#define __NR_NtQueryFullAttributesFile 228
#define __NR_NtQueryInformationAtom 229
#define __NR_NtQueryInformationEnlistment 230
#define __NR_NtQueryInformationFile 231
#define __NR_NtQueryInformationJobObject 232
#define __NR_NtQueryInformationPort 233
#define __NR_NtQueryInformationProcess 234
#define __NR_NtQueryInformationResourceManager 235
#define __NR_NtQueryInformationThread 236
#define __NR_NtQueryInformationToken 237
#define __NR_NtQueryInformationTransaction 238
#define __NR_NtQueryInformationTransactionManager 239
#define __NR_NtQueryInformationWorkerFactory 240
#define __NR_NtQueryInstallUILanguage 241
#define __NR_NtQueryIntervalProfile 242
#define __NR_NtQueryIoCompletion 243
#define __NR_NtQueryKey 244
#define __NR_NtQueryLicenseValue 245
#define __NR_NtQueryMultipleValueKey 246
#define __NR_NtQueryMutant 247
#define __NR_NtQueryObject 248
#define __NR_NtQueryOpenSubKeys 249
#define __NR_NtQueryOpenSubKeysEx 250
#define __NR_NtQueryPerformanceCounter 251
#define __NR_NtQueryPortInformationProcess 252
#define __NR_NtQueryQuotaInformationFile 253
#define __NR_NtQuerySection 254
#define __NR_NtQuerySecurityAttributesToken 255
#define __NR_NtQuerySecurityObject 256
#define __NR_NtQuerySemaphore 257
#define __NR_NtQuerySymbolicLinkObject 258
#define __NR_NtQuerySystemEnvironmentValue 259
#define __NR_NtQuerySystemEnvironmentValueEx 260
#define __NR_NtQuerySystemInformation 261
#define __NR_NtQuerySystemInformationEx 262
#define __NR_NtQuerySystemTime 263
#define __NR_NtQueryTimer 264
#define __NR_NtQueryTimerResolution 265
#define __NR_NtQueryValueKey 266
#define __NR_NtQueryVirtualMemory 267
#define __NR_NtQueryVolumeInformationFile 268
#define __NR_NtQueueApcThread 269
#define __NR_NtQueueApcThreadEx 270
#define __NR_NtRaiseException 271
#define __NR_NtRaiseHardError 272
#define __NR_NtReadFile 273
#define __NR_NtReadFileScatter 274
#define __NR_NtReadOnlyEnlistment 275
#define __NR_NtReadRequestData 276
#define __NR_NtReadVirtualMemory 277
#define __NR_NtRecoverEnlistment 278
#define __NR_NtRecoverResourceManager 279
#define __NR_NtRecoverTransactionManager 280
#define __NR_NtRegisterProtocolAddressInformation 281
#define __NR_NtRegisterThreadTerminatePort 282
#define __NR_NtReleaseKeyedEvent 283
#define __NR_NtReleaseMutant 284
#define __NR_NtReleaseSemaphore 285
#define __NR_NtReleaseWorkerFactoryWorker 286
#define __NR_NtRemoveIoCompletion 287
#define __NR_NtRemoveIoCompletionEx 288
#define __NR_NtRemoveProcessDebug 289
#define __NR_NtRenameKey 290
#define __NR_NtRenameTransactionManager 291
#define __NR_NtReplaceKey 292
#define __NR_NtReplacePartitionUnit 293
#define __NR_NtReplyPort 294
#define __NR_NtReplyWaitReceivePort 295
#define __NR_NtReplyWaitReceivePortEx 296
#define __NR_NtReplyWaitReplyPort 297
#define __NR_NtRequestPort 298
#define __NR_NtRequestWaitReplyPort 299
#define __NR_NtResetEvent 300
#define __NR_NtResetWriteWatch 301
#define __NR_NtRestoreKey 302
#define __NR_NtResumeProcess 303
#define __NR_NtResumeThread 304
#define __NR_NtRollbackComplete 305
#define __NR_NtRollbackEnlistment 306
#define __NR_NtRollbackTransaction 307
#define __NR_NtRollforwardTransactionManager 308
#define __NR_NtSaveKey 309
#define __NR_NtSaveKeyEx 310
#define __NR_NtSaveMergedKeys 311
#define __NR_NtSecureConnectPort 312
#define __NR_NtSerializeBoot 313
#define __NR_NtSetBootEntryOrder 314
#define __NR_NtSetBootOptions 315
#define __NR_NtSetContextThread 316
#define __NR_NtSetDebugFilterState 317
#define __NR_NtSetDefaultHardErrorPort 318
#define __NR_NtSetDefaultLocale 319
#define __NR_NtSetDefaultUILanguage 320
#define __NR_NtSetDriverEntryOrder 321
#define __NR_NtSetEaFile 322
#define __NR_NtSetEvent 323
#define __NR_NtSetEventBoostPriority 324
#define __NR_NtSetHighEventPair 325
#define __NR_NtSetHighWaitLowEventPair 326
#define __NR_NtSetInformationDebugObject 327
#define __NR_NtSetInformationEnlistment 328
#define __NR_NtSetInformationFile 329
#define __NR_NtSetInformationJobObject 330
#define __NR_NtSetInformationKey 331
#define __NR_NtSetInformationObject 332
#define __NR_NtSetInformationProcess 333
#define __NR_NtSetInformationResourceManager 334
#define __NR_NtSetInformationThread 335
#define __NR_NtSetInformationToken 336
#define __NR_NtSetInformationTransaction 337
#define __NR_NtSetInformationTransactionManager 338
#define __NR_NtSetInformationWorkerFactory 339
#define __NR_NtSetIntervalProfile 340
#define __NR_NtSetIoCompletion 341
#define __NR_NtSetIoCompletionEx 342
#define __NR_NtSetLdtEntries 343
#define __NR_NtSetLowEventPair 344
#define __NR_NtSetLowWaitHighEventPair 345
#define __NR_NtSetQuotaInformationFile 346
#define __NR_NtSetSecurityObject 347
#define __NR_NtSetSystemEnvironmentValue 348
#define __NR_NtSetSystemEnvironmentValueEx 349
#define __NR_NtSetSystemInformation 350
#define __NR_NtSetSystemPowerState 351
#define __NR_NtSetSystemTime 352
#define __NR_NtSetThreadExecutionState 353
#define __NR_NtSetTimer 354
#define __NR_NtSetTimerEx 355
#define __NR_NtSetTimerResolution 356
#define __NR_NtSetUuidSeed 357
#define __NR_NtSetValueKey 358
#define __NR_NtSetVolumeInformationFile 359
#define __NR_NtShutdownSystem 360
#define __NR_NtShutdownWorkerFactory 361
#define __NR_NtSignalAndWaitForSingleObject 362
#define __NR_NtSinglePhaseReject 363
#define __NR_NtStartProfile 364
#define __NR_NtStopProfile 365
#define __NR_NtSuspendProcess 366
#define __NR_NtSuspendThread 367
#define __NR_NtSystemDebugControl 368
#define __NR_NtTerminateJobObject 369
#define __NR_NtTerminateProcess 370
#define __NR_NtTerminateThread 371
#define __NR_NtTestAlert 372
#define __NR_NtThawRegistry 373
#define __NR_NtThawTransactions 374
#define __NR_NtTraceControl 375
#define __NR_NtTraceEvent 376
#define __NR_NtTranslateFilePath 377
#define __NR_NtUmsThreadYield 378
#define __NR_NtUnloadDriver 379
#define __NR_NtUnloadKey 380
#define __NR_NtUnloadKey2 381
#define __NR_NtUnloadKeyEx 382
#define __NR_NtUnlockFile 383
#define __NR_NtUnlockVirtualMemory 384
#define __NR_NtUnmapViewOfSection 385
#define __NR_NtVdmControl 386
#define __NR_NtWaitForDebugEvent 387
#define __NR_NtWaitForKeyedEvent 388
#define __NR_NtWaitForMultipleObjects 389
#define __NR_NtWaitForMultipleObjects32 390
#define __NR_NtWaitForSingleObject 391
#define __NR_NtWaitForWorkViaWorkerFactory 392
#define __NR_NtWaitHighEventPair 393
#define __NR_NtWaitLowEventPair 394
#define __NR_NtWorkerFactoryWorkerReady 395
#define __NR_NtWriteFile 396
#define __NR_NtWriteFileGather 397
#define __NR_NtWriteRequestData 398
#define __NR_NtWriteVirtualMemory 399
#define __NR_NtYieldExecution 400